package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * Pbcatedt generated by hbm2java
 */
public class Pbcatedt implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private PbcatedtId id;

	public Pbcatedt()
	{
	}

	public Pbcatedt(PbcatedtId id)
	{
		this.id = id;
	}

	public PbcatedtId getId()
	{
		return this.id;
	}

	public void setId(PbcatedtId id)
	{
		this.id = id;
	}

}
