package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * Pbcatcol generated by hbm2java
 */
public class Pbcatcol implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private PbcatcolId id;

	public Pbcatcol()
	{
	}

	public Pbcatcol(PbcatcolId id)
	{
		this.id = id;
	}

	public PbcatcolId getId()
	{
		return this.id;
	}

	public void setId(PbcatcolId id)
	{
		this.id = id;
	}

}
