package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * Pbcatvld generated by hbm2java
 */
public class Pbcatvld implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private PbcatvldId id;

	public Pbcatvld()
	{
	}

	public Pbcatvld(PbcatvldId id)
	{
		this.id = id;
	}

	public PbcatvldId getId()
	{
		return this.id;
	}

	public void setId(PbcatvldId id)
	{
		this.id = id;
	}

}
