package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * Pbcatfmt generated by hbm2java
 */
public class Pbcatfmt implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private PbcatfmtId id;

	public Pbcatfmt()
	{
	}

	public Pbcatfmt(PbcatfmtId id)
	{
		this.id = id;
	}

	public PbcatfmtId getId()
	{
		return this.id;
	}

	public void setId(PbcatfmtId id)
	{
		this.id = id;
	}

}
