package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * Pbcattbl generated by hbm2java
 */
public class Pbcattbl implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private PbcattblId id;

	public Pbcattbl()
	{
	}

	public Pbcattbl(PbcattblId id)
	{
		this.id = id;
	}

	public PbcattblId getId()
	{
		return this.id;
	}

	public void setId(PbcattblId id)
	{
		this.id = id;
	}

}
