package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlSdxqId generated by hbm2java
 */
public class SjygzlSdxqId implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private String fydm;
	private String ahdm;
	private Integer xh;

	public SjygzlSdxqId()
	{
	}


	public SjygzlSdxqId(String fydm, String ahdm) {
		super();
		this.fydm = fydm;
		this.ahdm = ahdm;
		this.xh = xh;
	}


	public String getFydm()
	{
		return this.fydm;
	}

	public void setFydm(String fydm)
	{
		this.fydm = fydm;
	}

	public String getAhdm()
	{
		return this.ahdm;
	}

	public void setAhdm(String ahdm)
	{
		this.ahdm = ahdm;
	}

	public Integer getXh() {
		return xh;
	}


	public void setXh(Integer xh) {
		this.xh = xh;
	}


	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SjygzlSdxqId))
			return false;
		SjygzlSdxqId castOther = (SjygzlSdxqId) other;

		return ((this.getFydm() == castOther.getFydm()) || (this.getFydm() != null
				&& castOther.getFydm() != null && this.getFydm().equals(
				castOther.getFydm())))
				&& ((this.getAhdm() == castOther.getAhdm()) || (this.getAhdm() != null
						&& castOther.getAhdm() != null && this.getAhdm()
						.equals(castOther.getAhdm())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result
				+ (getFydm() == null ? 0 : this.getFydm().hashCode());
		result = 37 * result
				+ (getAhdm() == null ? 0 : this.getAhdm().hashCode());
		result = 37 * result
				+ (getXh() == null ? 0 : this.getXh().hashCode());
		return result;
	}

}
