package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlKtxq generated by hbm2java
 */
public class SjygzlKtxq implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private SjygzlKtxqId id;
	private String ah;
	private String cbbm;
	private String cbbmmc;
	private String sjy;
	private String sjymc;
	private String dd;
	private String jssj;

	public SjygzlKtxq()
	{
	}

	public SjygzlKtxq(SjygzlKtxqId id)
	{
		this.id = id;
	}

	public SjygzlKtxq(SjygzlKtxqId id, String ah, String cbbm, String cbbmmc,
			String sjy, String sjymc, String dd, String jssj)
	{
		this.id = id;
		this.ah = ah;
		this.cbbm = cbbm;
		this.cbbmmc = cbbmmc;
		this.sjy = sjy;
		this.sjymc = sjymc;
		this.dd = dd;
		this.jssj = jssj;
	}

	public SjygzlKtxqId getId()
	{
		return this.id;
	}

	public void setId(SjygzlKtxqId id)
	{
		this.id = id;
	}

	public String getAh()
	{
		return this.ah;
	}

	public void setAh(String ah)
	{
		this.ah = ah;
	}

	public String getCbbm()
	{
		return this.cbbm;
	}

	public void setCbbm(String cbbm)
	{
		this.cbbm = cbbm;
	}

	public String getCbbmmc()
	{
		return this.cbbmmc;
	}

	public void setCbbmmc(String cbbmmc)
	{
		this.cbbmmc = cbbmmc;
	}

	public String getSjy()
	{
		return this.sjy;
	}

	public void setSjy(String sjy)
	{
		this.sjy = sjy;
	}

	public String getSjymc()
	{
		return this.sjymc;
	}

	public void setSjymc(String sjymc)
	{
		this.sjymc = sjymc;
	}

	public String getDd()
	{
		return this.dd;
	}

	public void setDd(String dd)
	{
		this.dd = dd;
	}

	public String getJssj()
	{
		return this.jssj;
	}

	public void setJssj(String jssj)
	{
		this.jssj = jssj;
	}

}
