package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlKtxqId generated by hbm2java
 */
public class SjygzlKtxqId implements java.io.Serializable
{

	private static final long serialVersionUID = 1L;

	private String fydm;
	private String ahdm;
	private String ktrq;
	private String kssj;

	public SjygzlKtxqId()
	{
	}

	public SjygzlKtxqId(String fydm, String ahdm, String ktrq, String kssj)
	{
		this.fydm = fydm;
		this.ahdm = ahdm;
		this.ktrq = ktrq;
		this.kssj = kssj;
	}

	public String getFydm()
	{
		return this.fydm;
	}

	public void setFydm(String fydm)
	{
		this.fydm = fydm;
	}

	public String getAhdm()
	{
		return this.ahdm;
	}

	public void setAhdm(String ahdm)
	{
		this.ahdm = ahdm;
	}

	public String getKtrq()
	{
		return this.ktrq;
	}

	public void setKtrq(String ktrq)
	{
		this.ktrq = ktrq;
	}

	public String getKssj()
	{
		return this.kssj;
	}

	public void setKssj(String kssj)
	{
		this.kssj = kssj;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SjygzlKtxqId))
			return false;
		SjygzlKtxqId castOther = (SjygzlKtxqId) other;

		return ((this.getFydm() == castOther.getFydm()) || (this.getFydm() != null
				&& castOther.getFydm() != null && this.getFydm().equals(
				castOther.getFydm())))
				&& ((this.getAhdm() == castOther.getAhdm()) || (this.getAhdm() != null
						&& castOther.getAhdm() != null && this.getAhdm()
						.equals(castOther.getAhdm())))
				&& ((this.getKtrq() == castOther.getKtrq()) || (this.getKtrq() != null
						&& castOther.getKtrq() != null && this.getKtrq()
						.equals(castOther.getKtrq())))
				&& ((this.getKssj() == castOther.getKssj()) || (this.getKssj() != null
						&& castOther.getKssj() != null && this.getKssj()
						.equals(castOther.getKssj())));
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result
				+ (getFydm() == null ? 0 : this.getFydm().hashCode());
		result = 37 * result
				+ (getAhdm() == null ? 0 : this.getAhdm().hashCode());
		result = 37 * result
				+ (getKtrq() == null ? 0 : this.getKtrq().hashCode());
		result = 37 * result
				+ (getKssj() == null ? 0 : this.getKssj().hashCode());
		return result;
	}

}
