package nju.software.sjy.model.tdh;

// Generated 2015-5-19 0:24:08 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlBlxq generated by hbm2java
 */
public class SjygzlBlxq implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;

	private SjygzlBlxqId id;
	private String ah;
	private String cbbm;
	private String cbbmmc;
	private String sjy;
	private String sjymc;
	private Integer wjzs;

	public SjygzlBlxq()
	{
	}

	public SjygzlBlxq(SjygzlBlxqId id)
	{
		this.id = id;
	}

	public SjygzlBlxq(SjygzlBlxqId id, String ah, String cbbm, String cbbmmc,
			String sjy, String sjymc, Integer wjzs)
	{
		this.id = id;
		this.ah = ah;
		this.cbbm = cbbm;
		this.cbbmmc = cbbmmc;
		this.sjy = sjy;
		this.sjymc = sjymc;
		this.wjzs = wjzs;
	}

	public SjygzlBlxqId getId()
	{
		return this.id;
	}

	public void setId(SjygzlBlxqId id)
	{
		this.id = id;
	}

	public String getAh()
	{
		return this.ah;
	}

	public void setAh(String ah)
	{
		this.ah = ah;
	}

	public String getCbbm()
	{
		return this.cbbm;
	}

	public void setCbbm(String cbbm)
	{
		this.cbbm = cbbm;
	}

	public String getCbbmmc()
	{
		return this.cbbmmc;
	}

	public void setCbbmmc(String cbbmmc)
	{
		this.cbbmmc = cbbmmc;
	}

	public String getSjy()
	{
		return this.sjy;
	}

	public void setSjy(String sjy)
	{
		this.sjy = sjy;
	}

	public String getSjymc()
	{
		return this.sjymc;
	}

	public void setSjymc(String sjymc)
	{
		this.sjymc = sjymc;
	}

	public Integer getWjzs()
	{
		return this.wjzs;
	}

	public void setWjzs(Integer wjzs)
	{
		this.wjzs = wjzs;
	}

}
