package nju.software.sjy.model.da;

// Generated 2015-5-22 15:44:48 by Hibernate Tools 3.4.0.CR1

/**
 * ViewDajgSsfzxx generated by hbm2java
 */
public class ViewDajgSsfzxx implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private String ahdm;
	private Integer zjys;
	private Integer fjys;

	public ViewDajgSsfzxx()
	{
	}

	public ViewDajgSsfzxx(String ahdm)
	{
		this.ahdm = ahdm;
	}

	public ViewDajgSsfzxx(String ahdm, Integer zjys, Integer fjys)
	{
		this.ahdm = ahdm;
		this.zjys = zjys;
		this.fjys = fjys;
	}

	public String getAhdm()
	{
		return this.ahdm;
	}

	public void setAhdm(String ahdm)
	{
		this.ahdm = ahdm;
	}

	public Integer getZjys()
	{
		return this.zjys;
	}

	public void setZjys(Integer zjys)
	{
		this.zjys = zjys;
	}

	public Integer getFjys()
	{
		return this.fjys;
	}

	public void setFjys(Integer fjys)
	{
		this.fjys = fjys;
	}

}
