package nju.software.sjy.model.xy;

// Generated 2016-1-9 0:52:06 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlSdxqId generated by hbm2java
 */
public class LocalSdxqId implements java.io.Serializable {

	private String fydm;
	private String ahdm;
	private String sdrq;
	private String sddsr;

	public LocalSdxqId() {
	}

	public LocalSdxqId(String fydm, String ahdm, String sdrq, String sddsr) {
		this.fydm = fydm;
		this.ahdm = ahdm;
		this.sdrq = sdrq;
		this.sddsr = sddsr;
	}

	public String getFydm() {
		return this.fydm;
	}

	public void setFydm(String fydm) {
		this.fydm = fydm;
	}

	public String getAhdm() {
		return this.ahdm;
	}

	public void setAhdm(String ahdm) {
		this.ahdm = ahdm;
	}

	public String getSdrq() {
		return this.sdrq;
	}

	public void setSdrq(String sdrq) {
		this.sdrq = sdrq;
	}

	public String getSddsr() {
		return sddsr;
	}

	public void setSddsr(String sddsr) {
		this.sddsr = sddsr;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ahdm == null) ? 0 : ahdm.hashCode());
		result = prime * result + ((fydm == null) ? 0 : fydm.hashCode());
		result = prime * result + ((sddsr == null) ? 0 : sddsr.hashCode());
		result = prime * result + ((sdrq == null) ? 0 : sdrq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LocalSdxqId other = (LocalSdxqId) obj;
		if (ahdm == null) {
			if (other.ahdm != null)
				return false;
		} else if (!ahdm.equals(other.ahdm))
			return false;
		if (fydm == null) {
			if (other.fydm != null)
				return false;
		} else if (!fydm.equals(other.fydm))
			return false;
		if (sddsr == null) {
			if (other.sddsr != null)
				return false;
		} else if (!sddsr.equals(other.sddsr))
			return false;
		if (sdrq == null) {
			if (other.sdrq != null)
				return false;
		} else if (!sdrq.equals(other.sdrq))
			return false;
		return true;
	}



}
