package nju.software.sjy.model.xy;

// Generated 2016-1-9 0:52:06 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlSdxqId generated by hbm2java
 */
public class SjygzlSdxqId implements java.io.Serializable {

	private String fydm;
	private String ahdm;
	private String sdrq;
	private String sdddsr;

	public SjygzlSdxqId() {
	}

	public SjygzlSdxqId(String fydm, String ahdm, String sdrq, String sdddsr) {
		this.fydm = fydm;
		this.ahdm = ahdm;
		this.sdrq = sdrq;
		this.sdddsr = sdddsr;
	}

	public String getFydm() {
		return this.fydm;
	}

	public void setFydm(String fydm) {
		this.fydm = fydm;
	}

	public String getAhdm() {
		return this.ahdm;
	}

	public void setAhdm(String ahdm) {
		this.ahdm = ahdm;
	}

	public String getSdrq() {
		return this.sdrq;
	}

	public void setSdrq(String sdrq) {
		this.sdrq = sdrq;
	}

	public String getSdddsr() {
		return this.sdddsr;
	}

	public void setSdddsr(String sdddsr) {
		this.sdddsr = sdddsr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SjygzlSdxqId))
			return false;
		SjygzlSdxqId castOther = (SjygzlSdxqId) other;

		return ((this.getFydm() == castOther.getFydm()) || (this.getFydm() != null
				&& castOther.getFydm() != null && this.getFydm().equals(
				castOther.getFydm())))
				&& ((this.getAhdm() == castOther.getAhdm()) || (this.getAhdm() != null
						&& castOther.getAhdm() != null && this.getAhdm()
						.equals(castOther.getAhdm())))
				&& ((this.getSdrq() == castOther.getSdrq()) || (this.getSdrq() != null
						&& castOther.getSdrq() != null && this.getSdrq()
						.equals(castOther.getSdrq())))
				&& ((this.getSdddsr() == castOther.getSdddsr()) || (this
						.getSdddsr() != null && castOther.getSdddsr() != null && this
						.getSdddsr().equals(castOther.getSdddsr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFydm() == null ? 0 : this.getFydm().hashCode());
		result = 37 * result
				+ (getAhdm() == null ? 0 : this.getAhdm().hashCode());
		result = 37 * result
				+ (getSdrq() == null ? 0 : this.getSdrq().hashCode());
		result = 37 * result
				+ (getSdddsr() == null ? 0 : this.getSdddsr().hashCode());
		return result;
	}

}
