package nju.software.sjy.model.xy;

// Generated 2016-1-9 0:52:06 by Hibernate Tools 3.4.0.CR1

/**
 * SjygzlAjxx generated by hbm2java
 */
public class SjygzlAjxx implements java.io.Serializable {

	private SjygzlAjxxId id;
	private String ah;
	private String cbbm;
	private String cbbmmc;
	private String sjy;
	private String sjymc;
	private String xzsjy;
	private String xzsjymc;
	private String larq;
	private String jarq;
	private String tjgdrq;
	private String gdjsrq;

	public SjygzlAjxx() {
	}

	public SjygzlAjxx(SjygzlAjxxId id) {
		this.id = id;
	}

	public SjygzlAjxx(SjygzlAjxxId id, String ah, String cbbm, String cbbmmc,
			String sjy, String sjymc, String xzsjy, String xzsjymc,
			String larq, String jarq, String tjgdrq, String gdjsrq) {
		this.id = id;
		this.ah = ah;
		this.cbbm = cbbm;
		this.cbbmmc = cbbmmc;
		this.sjy = sjy;
		this.sjymc = sjymc;
		this.xzsjy = xzsjy;
		this.xzsjymc = xzsjymc;
		this.larq = larq;
		this.jarq = jarq;
		this.tjgdrq = tjgdrq;
		this.gdjsrq = gdjsrq;
	}

	public SjygzlAjxxId getId() {
		return this.id;
	}

	public void setId(SjygzlAjxxId id) {
		this.id = id;
	}

	public String getAh() {
		return this.ah;
	}

	public void setAh(String ah) {
		this.ah = ah;
	}

	public String getCbbm() {
		return this.cbbm;
	}

	public void setCbbm(String cbbm) {
		this.cbbm = cbbm;
	}

	public String getCbbmmc() {
		return this.cbbmmc;
	}

	public void setCbbmmc(String cbbmmc) {
		this.cbbmmc = cbbmmc;
	}

	public String getSjy() {
		return this.sjy;
	}

	public void setSjy(String sjy) {
		this.sjy = sjy;
	}

	public String getSjymc() {
		return this.sjymc;
	}

	public void setSjymc(String sjymc) {
		this.sjymc = sjymc;
	}

	public String getXzsjy() {
		return this.xzsjy;
	}

	public void setXzsjy(String xzsjy) {
		this.xzsjy = xzsjy;
	}

	public String getXzsjymc() {
		return this.xzsjymc;
	}

	public void setXzsjymc(String xzsjymc) {
		this.xzsjymc = xzsjymc;
	}

	public String getLarq() {
		return this.larq;
	}

	public void setLarq(String larq) {
		this.larq = larq;
	}

	public String getJarq() {
		return this.jarq;
	}

	public void setJarq(String jarq) {
		this.jarq = jarq;
	}

	public String getTjgdrq() {
		return this.tjgdrq;
	}

	public void setTjgdrq(String tjgdrq) {
		this.tjgdrq = tjgdrq;
	}

	public String getGdjsrq() {
		return this.gdjsrq;
	}

	public void setGdjsrq(String gdjsrq) {
		this.gdjsrq = gdjsrq;
	}

}
