package nju.software.sjy.model.xy;

// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1

/**
 * TBm generated by hbm2java
 */
public class TBm implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int bmbh;
	private String bmid;
	private String bmmc;
	private TGypz bmlx;

	public TBm()
	{
	}
	
	public TBm(int bmbh, String bmmc)
	{
		this.bmbh = bmbh;
		this.bmmc = bmmc;
	}

	public TBm(int bmbh, String bmid, String bmmc, TGypz bmlx)
	{
		this.bmbh = bmbh;
		this.bmid = bmid;
		this.bmmc = bmmc;
		this.bmlx = bmlx;
	}

	public int getBmbh()
	{
		return this.bmbh;
	}

	public void setBmbh(int bmbh)
	{
		this.bmbh = bmbh;
	}

	public String getBmid()
	{
		return bmid;
	}

	public void setBmid(String bmid)
	{
		this.bmid = bmid;
	}

	public String getBmmc()
	{
		return this.bmmc;
	}

	public void setBmmc(String bmmc)
	{
		this.bmmc = bmmc;
	}

	public TGypz getBmlx()
	{
		return bmlx;
	}

	public void setBmlx(TGypz bmlx)
	{
		this.bmlx = bmlx;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + bmbh;
		result = prime * result + ((bmmc == null) ? 0 : bmmc.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TBm other = (TBm) obj;
		if (bmbh != other.bmbh)
			return false;
		if (bmmc == null) {
			if (other.bmmc != null)
				return false;
		} else if (!bmmc.equals(other.bmmc))
			return false;
		return true;
	}
	

}
