package nju.software.sjy.model.xy;

// Generated 2015-3-4 14:59:48 by Hibernate Tools 3.4.0.CR1

/**
 * TGztb generated by hbm2java
 */
public class TGzsjxx implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int bh;
	private TGzsj gzsj;
	private TGypz gzxx;
	private int sz;

	public TGzsjxx()
	{
	}


	public TGzsjxx(int bh, TGzsj gzsj, TGypz gzxx, int sz)
	{
		this.bh = bh;
		this.gzsj = gzsj;
		this.gzxx = gzxx;
		this.sz = sz;
	}

	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public TGzsj getGzsj()
	{
		return gzsj;
	}


	public void setGzsj(TGzsj gzsj)
	{
		this.gzsj = gzsj;
	}


	public TGypz getGzxx()
	{
		return gzxx;
	}

	public void setGzxx(TGypz gzxx)
	{
		this.gzxx = gzxx;
	}

	public int getSz()
	{
		return this.sz;
	}

	public void setSz(int sz)
	{
		this.sz = sz;
	}

}
