package nju.software.sjy.model.xy;

import java.util.ArrayList;
import java.util.List;

// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1

/**
 * TGzsj generated by hbm2java
 */
public class TGzsj implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int bh;
	private TUser user;
	private TBm bm;
	private String rq;
	private int edit;
	private TGypz zt;
	private List<TGzsjxx> xxList = new ArrayList<TGzsjxx>();

	public TGzsj()
	{
	}
	

	



	public TGzsj(int bh, TUser user, TBm bm, String rq, int edit, TGypz zt) {

		this.bh = bh;
		this.user = user;
		this.bm = bm;
		this.rq = rq;
		this.edit = edit;
		this.zt = zt;
		
	}






	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public TUser getUser()
	{
		return user;
	}

	public void setUser(TUser user)
	{
		this.user = user;
	}

	public TBm getBm()
	{
		return bm;
	}

	public void setBm(TBm bm)
	{
		this.bm = bm;
	}

	public String getRq()
	{
		return this.rq;
	}

	public void setRq(String rq)
	{
		this.rq = rq;
	}

	public TGypz getZt()
	{
		return zt;
	}

	public void setZt(TGypz zt)
	{
		this.zt = zt;
	}

	public List<TGzsjxx> getXxList()
	{
		return xxList;
	}

	public void setXxList(List<TGzsjxx> xxList)
	{
		this.xxList = xxList;
	}
	
	public int getEdit() {
		return edit;
	}

	public void setEdit(int edit) {
		this.edit = edit;
	}

}
