package nju.software.sjy.model.xy;

// Generated Mar 16, 2015 12:08:21 AM by Hibernate Tools 3.4.0.CR1

/**
 * TJfpz generated by hbm2java
 */
public class TJfpz implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int bh;
	private String jb;
	private int jfz;

	public TJfpz()
	{
	}

	public TJfpz(int bh, String jb, int jfz)
	{
		this.bh = bh;
		this.jb = jb;
		this.jfz = jfz;
	}

	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public String getJb()
	{
		return this.jb;
	}

	public void setJb(String jb)
	{
		this.jb = jb;
	}

	public int getJfz()
	{
		return this.jfz;
	}

	public void setJfz(int jfz)
	{
		this.jfz = jfz;
	}

}
