package nju.software.sjy.model.xy;

// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1


/**
 * TJfqx generated by hbm2java
 */
public class TJfqx implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int bh;
	private TUser user;
	private TBm bm;
	private int nf;
	private int yf;
	private int jfcs;
	private String hdsj;
	private TGypz zt;
	private TJfkfxm jfxm;
	private String comment;

	public TJfqx()
	{
	}

	public int getBh()
	{
		return bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public TUser getUser()
	{
		return user;
	}

	public void setUser(TUser user)
	{
		this.user = user;
	}

	public TBm getBm()
	{
		return bm;
	}

	public void setBm(TBm bm)
	{
		this.bm = bm;
	}

	public int getNf()
	{
		return nf;
	}

	public void setNf(int nf)
	{
		this.nf = nf;
	}

	public int getYf()
	{
		return yf;
	}

	public void setYf(int yf)
	{
		this.yf = yf;
	}

	public int getJfcs()
	{
		return jfcs;
	}

	public void setJfcs(int jfcs)
	{
		this.jfcs = jfcs;
	}

	public String getHdsj()
	{
		return hdsj;
	}

	public void setHdsj(String hdsj)
	{
		this.hdsj = hdsj;
	}

	public TGypz getZt()
	{
		return zt;
	}

	public void setZt(TGypz zt)
	{
		this.zt = zt;
	}

	public TJfkfxm getJfxm()
	{
		return jfxm;
	}

	public void setJfxm(TJfkfxm jfxm)
	{
		this.jfxm = jfxm;
	}

	public String getComment()
	{
		return comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	

}