package nju.software.sjy.model.xy;

// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1


/**
 * TJfqx generated by hbm2java
 */
public class TKfqx implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int bh;
	private TUser ry;
	private TBm bm;
	private int nf;
	private int yf;
	private int kfcs;
	private String hdsj;
	private TJfkfxm kfxm;
	private String comment;

	public TKfqx()
	{
	}

	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public int getNf()
	{
		return this.nf;
	}

	public void setNf(int nf)
	{
		this.nf = nf;
	}

	public int getYf()
	{
		return this.yf;
	}

	public void setYf(int yf)
	{
		this.yf = yf;
	}

	public int getKfcs()
	{
		return kfcs;
	}

	public void setKfcs(int kfcs)
	{
		this.kfcs = kfcs;
	}

	public String getHdsj()
	{
		return this.hdsj;
	}

	public void setHdsj(String hdsj)
	{
		this.hdsj = hdsj;
	}

	public TJfkfxm getKfxm() {
		return kfxm;
	}

	public void setKfxm(TJfkfxm kfxm) {
		this.kfxm = kfxm;
	}

	public TBm getBm() {
		return bm;
	}

	public void setBm(TBm bm) {
		this.bm = bm;
	}

	public TUser getRy() {
		return ry;
	}

	public void setRy(TUser ry) {
		this.ry = ry;
	}

	public String getComment()
	{
		return comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

}
