package nju.software.sjy.model.xy;

// Generated Mar 27, 2015 2:10:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * TMethod generated by hbm2java
 */
public class TMethod implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int methodbh;
	private String classname;
	private String methodname;

	public TMethod()
	{
	}

	public TMethod(int methodbh, String classname, String methodname)
	{
		this.methodbh = methodbh;
		this.classname = classname;
		this.methodname = methodname;
	}

	public int getMethodbh()
	{
		return this.methodbh;
	}

	public void setMethodbh(int methodbh)
	{
		this.methodbh = methodbh;
	}

	public String getClassname()
	{
		return this.classname;
	}

	public void setClassname(String classname)
	{
		this.classname = classname;
	}

	public String getMethodname()
	{
		return this.methodname;
	}

	public void setMethodname(String methodname)
	{
		this.methodname = methodname;
	}

}
