package nju.software.sjy.model.xy;

//Generated Mar 27, 2015 2:10:41 PM by Hibernate Tools 3.4.0.CR1

/**
* TOperation generated by hbm2java
*/

public class TOperation implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int bh;
	private String name;
	private TGypz range;
	private String alias;
	private Integer status;
	
	public TOperation()
	{
		
	}

	public int getBh()
	{
		return bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public TGypz getRange()
	{
		return range;
	}

	public void setRange(TGypz range)
	{
		this.range = range;
	}

	public String getAlias()
	{
		return alias;
	}

	public void setAlias(String alias)
	{
		this.alias = alias;
	}

	public Integer getStatus()
	{
		return status;
	}

	public void setStatus(Integer status)
	{
		this.status = status;
	}
	
	
}
