package nju.software.sjy.model.xy;

// Generated 2015-3-18 19:47:53 by Hibernate Tools 3.4.0.CR1

/**
 * TPfkh generated by hbm2java
 */
public class TPfkh implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int bh;
	private TUser user;
	private int nf;
	private int jd;
	private Double jddf;

	public TPfkh()
	{
	}

	public TPfkh(int bh, TUser user, int nf, int jd)
	{
		this.bh = bh;
		this.user = user;
		this.nf = nf;
		this.jd = jd;
	}

	public TPfkh(int bh, TUser user, int nf, int jd, Double jddf)
	{
		this.bh = bh;
		this.user = user;
		this.nf = nf;
		this.jd = jd;
		this.jddf = jddf;
	}

	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public TUser getUser()
	{
		return user;
	}

	public void setUser(TUser user)
	{
		this.user = user;
	}

	public int getNf()
	{
		return this.nf;
	}

	public void setNf(int nf)
	{
		this.nf = nf;
	}

	public int getJd()
	{
		return this.jd;
	}

	public void setJd(int jd)
	{
		this.jd = jd;
	}

	public Double getJddf()
	{
		return this.jddf;
	}

	public void setJddf(Double jddf)
	{
		this.jddf = jddf;
	}

}
