package nju.software.sjy.model.xy;

// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1

/**
 * TPfpz generated by hbm2java
 */
public class TPfpz implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int bh;
	private TGypz gz;
	private int fs;

	public TPfpz()
	{
	}

	public TPfpz(int bh, TGypz gz, int fs)
	{
		this.bh = bh;
		this.gz = gz;
		this.fs = fs;
	}

	public int getBh()
	{
		return this.bh;
	}

	public void setBh(int bh)
	{
		this.bh = bh;
	}

	public TGypz getGz() 
	{
		return gz;
	}

	public void setGz(TGypz gz) 
	{
		this.gz = gz;
	}

	public int getFs()
	{
		return this.fs;
	}

	public void setFs(int fs)
	{
		this.fs = fs;
	}

}
