package nju.software.sjy.model.xy;

// Generated Mar 27, 2015 2:10:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int rolebh;
	private String rolename;
	private Integer levels;

	public TRole()
	{
	}

	public TRole(int rolebh, String rolename)
	{
		this.rolebh = rolebh;
		this.rolename = rolename;
	}

	public TRole(int rolebh, String rolename, Integer levels)
	{
		this.rolebh = rolebh;
		this.rolename = rolename;
		this.levels = levels;
	}
	
	@Override
	public boolean equals(Object obj)
	{
		if(obj instanceof TRole)
		{
			TRole target = (TRole)obj;
			if(this.rolebh == target.getRolebh() && this.rolename.equals(target.getRolename())
					&& this.levels.equals(target.getLevels()))
			{
				return true;
			}
		}
		return false;
	}
	
	@Override
	public int hashCode()
	{
		int result = 17;
		result = 37 * result + rolebh;
		result = 37 * result + rolename.hashCode();
		result = 37 * result + levels.hashCode();
		
		return result;
	}

	public int getRolebh()
	{
		return this.rolebh;
	}

	public void setRolebh(int rolebh)
	{
		this.rolebh = rolebh;
	}

	public String getRolename()
	{
		return this.rolename;
	}

	public void setRolename(String rolename)
	{
		this.rolename = rolename;
	}

	public Integer getLevels()
	{
		return this.levels;
	}

	public void setLevels(Integer levels)
	{
		this.levels = levels;
	}

}
