package nju.software.sjy.model.xy;

// Generated Mar 27, 2015 2:10:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * TRolemethod generated by hbm2java
 */
public class TRolemethod implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
	private int rmbh;
	private TRole role;
	private TMethod method;

	public TRolemethod()
	{
	}

	public TRolemethod(int rmbh, TRole role, TMethod method)
	{
		this.rmbh = rmbh;
		this.role = role;
		this.method = method;
	}

	public int getRmbh()
	{
		return this.rmbh;
	}

	public void setRmbh(int rmbh)
	{
		this.rmbh = rmbh;
	}

	public TRole getRole()
	{
		return role;
	}

	public void setRole(TRole role)
	{
		this.role = role;
	}

	public TMethod getMethod()
	{
		return method;
	}

	public void setMethod(TMethod method)
	{
		this.method = method;
	}

	
}
