package nju.software.sjy.model.xy;

// Generated 2015-3-2 17:43:59 by Hibernate Tools 3.4.0.CR1

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private int rybh;
	private String xm;
	private TBm bm;
	private String username;
	private String password;
	private String yhsf;
	private TRole role;
	private String userid;

	public TUser()
	{
	}

	public TUser(int rybh, String xm, TBm bm, String username, String password, TRole role)
	{
		this.rybh = rybh;
		this.xm = xm;
		this.bm = bm;
		this.username = username;
		this.password = password;
		this.role = role;
	}

	public TUser(int rybh, String xm, TBm bm, String username, String password, String yhsf, TRole role)
	{
		this.rybh = rybh;
		this.xm = xm;
		this.bm = bm;
		this.username = username;
		this.password = password;
		this.yhsf = yhsf;
		this.role = role;
	}

	public int getRybh()
	{
		return this.rybh;
	}

	public void setRybh(int rybh)
	{
		this.rybh = rybh;
	}

	public String getXm()
	{
		return this.xm;
	}

	public void setXm(String xm)
	{
		this.xm = xm;
	}

	public TBm getBm()
	{
		return bm;
	}

	public void setBm(TBm bm)
	{
		this.bm = bm;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String getYhsf()
	{
		return this.yhsf;
	}

	public void setYhsf(String yhsf)
	{
		this.yhsf = yhsf;
	}

	public String getUsername()
	{
		return username;
	}

	public void setUsername(String username)
	{
		this.username = username;
	}

	public TRole getRole() 
	{
		return role;
	}

	public void setRole(TRole role) 
	{
		this.role = role;
	}

	public String getUserid()
	{
		return userid;
	}

	public void setUserid(String userid)
	{
		this.userid = userid;
	}

}
