
package nju.software.sjy.webservice.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-28T16:56:12.292+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class SzftWebService_SzftWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://szft.tdh/", "SzftWebServiceService");

    private SzftWebService_SzftWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SzftWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SzftWebServiceService ss = new SzftWebServiceService(wsdlURL, SERVICE_NAME);
        SzftWebService port = ss.getSzftWebServicePort();  
        
        {
        System.out.println("Invoking getJzMl...");
        java.lang.String _getJzMl_userid = "";
        java.lang.String _getJzMl_pwd = "";
        java.lang.String _getJzMl_requestXML = "";
        java.lang.String _getJzMl__return = port.getJzMl(_getJzMl_userid, _getJzMl_pwd, _getJzMl_requestXML);
        System.out.println("getJzMl.result=" + _getJzMl__return);


        }
        {
        System.out.println("Invoking getPlKt...");
        java.lang.String _getPlKt_userid = "";
        java.lang.String _getPlKt_pwd = "";
        java.lang.String _getPlKt_requestXML = "";
        java.lang.String _getPlKt__return = port.getPlKt(_getPlKt_userid, _getPlKt_pwd, _getPlKt_requestXML);
        System.out.println("getPlKt.result=" + _getPlKt__return);


        }
        {
        System.out.println("Invoking getFt...");
        java.lang.String _getFt_uid = "";
        java.lang.String _getFt_pass = "";
        java.lang.String _getFt_xml = "";
        java.lang.String _getFt__return = port.getFt(_getFt_uid, _getFt_pass, _getFt_xml);
        System.out.println("getFt.result=" + _getFt__return);


        }
        {
        System.out.println("Invoking getAllSjy...");
        java.lang.String _getAllSjy_uid = "";
        java.lang.String _getAllSjy_pass = "";
        java.lang.String _getAllSjy_resultXMLVal = "";
        javax.xml.ws.Holder<java.lang.String> _getAllSjy_resultXML = new javax.xml.ws.Holder<java.lang.String>(_getAllSjy_resultXMLVal);
        port.getAllSjy(_getAllSjy_uid, _getAllSjy_pass, _getAllSjy_resultXML);

        System.out.println("getAllSjy._getAllSjy_resultXML=" + _getAllSjy_resultXML.value);

        }
        {
        System.out.println("Invoking getHjm...");
        java.lang.String _getHjm_userid = "";
        java.lang.String _getHjm_pwd = "";
        java.lang.String _getHjm_requestXML = "";
        java.lang.String _getHjm__return = port.getHjm(_getHjm_userid, _getHjm_pwd, _getHjm_requestXML);
        System.out.println("getHjm.result=" + _getHjm__return);


        }
        {
        System.out.println("Invoking saveYdktPqxx...");
        java.lang.String _saveYdktPqxx_uid = "";
        java.lang.String _saveYdktPqxx_pwd = "";
        java.lang.String _saveYdktPqxx_xml = "";
        java.lang.String _saveYdktPqxx__return = port.saveYdktPqxx(_saveYdktPqxx_uid, _saveYdktPqxx_pwd, _saveYdktPqxx_xml);
        System.out.println("saveYdktPqxx.result=" + _saveYdktPqxx__return);


        }
        {
        System.out.println("Invoking sendKtxxZj...");
        java.lang.String _sendKtxxZj_userid = "";
        java.lang.String _sendKtxxZj_pwd = "";
        java.lang.String _sendKtxxZj_requestXml = "";
        java.lang.String _sendKtxxZj__return = port.sendKtxxZj(_sendKtxxZj_userid, _sendKtxxZj_pwd, _sendKtxxZj_requestXml);
        System.out.println("sendKtxxZj.result=" + _sendKtxxZj__return);


        }
        {
        System.out.println("Invoking getZzjg...");
        java.lang.String _getZzjg_userid = "";
        java.lang.String _getZzjg_pwd = "";
        java.lang.String _getZzjg_requestXML = "";
        java.lang.String _getZzjg__return = port.getZzjg(_getZzjg_userid, _getZzjg_pwd, _getZzjg_requestXML);
        System.out.println("getZzjg.result=" + _getZzjg__return);


        }
        {
        System.out.println("Invoking getAjfl...");
        java.lang.String _getAjfl_userid = "";
        java.lang.String _getAjfl_pwd = "";
        java.lang.String _getAjfl_requestXML = "";
        java.lang.String _getAjfl__return = port.getAjfl(_getAjfl_userid, _getAjfl_pwd, _getAjfl_requestXML);
        System.out.println("getAjfl.result=" + _getAjfl__return);


        }
        {
        System.out.println("Invoking getRy...");
        java.lang.String _getRy_userid = "";
        java.lang.String _getRy_pwd = "";
        java.lang.String _getRy_requestXML = "";
        java.lang.String _getRy__return = port.getRy(_getRy_userid, _getRy_pwd, _getRy_requestXML);
        System.out.println("getRy.result=" + _getRy__return);


        }
        {
        System.out.println("Invoking getPlAj...");
        java.lang.String _getPlAj_userid = "";
        java.lang.String _getPlAj_pwd = "";
        java.lang.String _getPlAj_requestXML = "";
        java.lang.String _getPlAj__return = port.getPlAj(_getPlAj_userid, _getPlAj_pwd, _getPlAj_requestXML);
        System.out.println("getPlAj.result=" + _getPlAj__return);


        }
        {
        System.out.println("Invoking getSjyGzl...");
        java.lang.String _getSjyGzl_uid = "";
        java.lang.String _getSjyGzl_pass = "";
        java.lang.String _getSjyGzl_resultXMLVal = "";
        javax.xml.ws.Holder<java.lang.String> _getSjyGzl_resultXML = new javax.xml.ws.Holder<java.lang.String>(_getSjyGzl_resultXMLVal);
        port.getSjyGzl(_getSjyGzl_uid, _getSjyGzl_pass, _getSjyGzl_resultXML);

        System.out.println("getSjyGzl._getSjyGzl_resultXML=" + _getSjyGzl_resultXML.value);

        }
        {
        System.out.println("Invoking tszbZtfk...");
        java.lang.String _tszbZtfk_userid = "";
        java.lang.String _tszbZtfk_pwd = "";
        java.lang.String _tszbZtfk_requestXml = "";
        java.lang.String _tszbZtfk__return = port.tszbZtfk(_tszbZtfk_userid, _tszbZtfk_pwd, _tszbZtfk_requestXml);
        System.out.println("tszbZtfk.result=" + _tszbZtfk__return);


        }
        {
        System.out.println("Invoking sendKtxx...");
        java.lang.String _sendKtxx_userid = "";
        java.lang.String _sendKtxx_pwd = "";
        java.lang.String _sendKtxx_requestXml = "";
        java.lang.String _sendKtxx__return = port.sendKtxx(_sendKtxx_userid, _sendKtxx_pwd, _sendKtxx_requestXml);
        System.out.println("sendKtxx.result=" + _sendKtxx__return);


        }
        {
        System.out.println("Invoking getGxajByZdsj...");
        java.lang.String _getGxajByZdsj_userid = "";
        java.lang.String _getGxajByZdsj_pwd = "";
        java.lang.String _getGxajByZdsj_requestXML = "";
        java.lang.String _getGxajByZdsj__return = port.getGxajByZdsj(_getGxajByZdsj_userid, _getGxajByZdsj_pwd, _getGxajByZdsj_requestXML);
        System.out.println("getGxajByZdsj.result=" + _getGxajByZdsj__return);


        }
        {
        System.out.println("Invoking delKtxx...");
        java.lang.String _delKtxx_userid = "";
        java.lang.String _delKtxx_pwd = "";
        java.lang.String _delKtxx_requestXML = "";
        java.lang.String _delKtxx__return = port.delKtxx(_delKtxx_userid, _delKtxx_pwd, _delKtxx_requestXML);
        System.out.println("delKtxx.result=" + _delKtxx__return);


        }
        {
        System.out.println("Invoking getTsbl...");
        java.lang.String _getTsbl_userid = "";
        java.lang.String _getTsbl_pwd = "";
        java.lang.String _getTsbl_requestXML = "";
        java.lang.String _getTsbl__return = port.getTsbl(_getTsbl_userid, _getTsbl_pwd, _getTsbl_requestXML);
        System.out.println("getTsbl.result=" + _getTsbl__return);


        }
        {
        System.out.println("Invoking getDsr...");
        java.lang.String _getDsr_userid = "";
        java.lang.String _getDsr_pwd = "";
        java.lang.String _getDsr_requestXML = "";
        java.lang.String _getDsr__return = port.getDsr(_getDsr_userid, _getDsr_pwd, _getDsr_requestXML);
        System.out.println("getDsr.result=" + _getDsr__return);


        }
        {
        System.out.println("Invoking getJzNr...");
        java.lang.String _getJzNr_userid = "";
        java.lang.String _getJzNr_pwd = "";
        java.lang.String _getJzNr_requestXML = "";
        java.lang.String _getJzNr__return = port.getJzNr(_getJzNr_userid, _getJzNr_pwd, _getJzNr_requestXML);
        System.out.println("getJzNr.result=" + _getJzNr__return);


        }
        {
        System.out.println("Invoking sendVideo...");
        java.lang.String _sendVideo_uid = "";
        java.lang.String _sendVideo_pass = "";
        java.lang.String _sendVideo_xml = "";
        java.lang.String _sendVideo__return = port.sendVideo(_sendVideo_uid, _sendVideo_pass, _sendVideo_xml);
        System.out.println("sendVideo.result=" + _sendVideo__return);


        }

        System.exit(0);
    }

}
