package nju.software.sjy.webservice.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-28T16:56:12.341+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://szft.tdh/", name = "SzftWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SzftWebService {

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetJzMl")
    public java.lang.String getJzMl(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetPlKt")
    public java.lang.String getPlKt(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetFt")
    public java.lang.String getFt(
        @WebParam(partName = "uid", name = "uid")
        java.lang.String uid,
        @WebParam(partName = "pass", name = "pass")
        java.lang.String pass,
        @WebParam(partName = "xml", name = "xml")
        java.lang.String xml
    );

    @WebMethod(operationName = "GetAllSjy")
    public void getAllSjy(
        @WebParam(partName = "uid", name = "uid")
        java.lang.String uid,
        @WebParam(partName = "pass", name = "pass")
        java.lang.String pass,
        @WebParam(partName = "ResultXML", mode = WebParam.Mode.INOUT, name = "ResultXML")
        javax.xml.ws.Holder<java.lang.String> resultXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetHjm")
    public java.lang.String getHjm(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "SaveYdktPqxx")
    public java.lang.String saveYdktPqxx(
        @WebParam(partName = "uid", name = "uid")
        java.lang.String uid,
        @WebParam(partName = "pwd", name = "pwd")
        java.lang.String pwd,
        @WebParam(partName = "XML", name = "XML")
        java.lang.String xml
    );

    @WebResult(name = "Result", targetNamespace = "http://szft.tdh/", partName = "Result")
    @WebMethod(operationName = "SendKtxx_zj")
    public java.lang.String sendKtxxZj(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXml", name = "RequestXml")
        java.lang.String requestXml
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetZzjg")
    public java.lang.String getZzjg(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetAjfl")
    public java.lang.String getAjfl(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetRy")
    public java.lang.String getRy(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetPlAj")
    public java.lang.String getPlAj(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebMethod(operationName = "GetSjyGzl")
    public void getSjyGzl(
        @WebParam(partName = "uid", name = "uid")
        java.lang.String uid,
        @WebParam(partName = "pass", name = "pass")
        java.lang.String pass,
        @WebParam(partName = "ResultXML", mode = WebParam.Mode.INOUT, name = "ResultXML")
        javax.xml.ws.Holder<java.lang.String> resultXML
    );

    @WebResult(name = "Result", targetNamespace = "http://szft.tdh/", partName = "Result")
    @WebMethod(operationName = "TszbZtfk")
    public java.lang.String tszbZtfk(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXml", name = "RequestXml")
        java.lang.String requestXml
    );

    @WebResult(name = "Result", targetNamespace = "http://szft.tdh/", partName = "Result")
    @WebMethod(operationName = "SendKtxx")
    public java.lang.String sendKtxx(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXml", name = "RequestXml")
        java.lang.String requestXml
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetGxajByZdsj")
    public java.lang.String getGxajByZdsj(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "DelKtxx")
    public java.lang.String delKtxx(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetTsbl")
    public java.lang.String getTsbl(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetDsr")
    public java.lang.String getDsr(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "GetJzNr")
    public java.lang.String getJzNr(
        @WebParam(partName = "Userid", name = "Userid")
        java.lang.String userid,
        @WebParam(partName = "Pwd", name = "Pwd")
        java.lang.String pwd,
        @WebParam(partName = "RequestXML", name = "RequestXML")
        java.lang.String requestXML
    );

    @WebResult(name = "ResultXML", targetNamespace = "http://szft.tdh/", partName = "ResultXML")
    @WebMethod(operationName = "SendVideo")
    public java.lang.String sendVideo(
        @WebParam(partName = "uid", name = "uid")
        java.lang.String uid,
        @WebParam(partName = "pass", name = "pass")
        java.lang.String pass,
        @WebParam(partName = "xml", name = "xml")
        java.lang.String xml
    );
}
