
package nju.software.sjy.webservice.cxf;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-28T16:56:12.355+08:00
 * Generated source version: 3.0.4
 * 
 */
 
public class SzftWebService_SzftWebServicePort_Server{

    protected SzftWebService_SzftWebServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SzftWebServicePortImpl();
        String address = "http://200.100.48.28:81/court/service/SzftWebService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SzftWebService_SzftWebServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
