package nju.software.sjy.webservice.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-28T16:56:12.359+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "SzftWebServiceService", 
                  wsdlLocation = "http://200.100.48.28:81/court/service/SzftWebService?wsdl",
                  targetNamespace = "http://szft.tdh/") 
public class SzftWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://szft.tdh/", "SzftWebServiceService");
    public final static QName SzftWebServicePort = new QName("http://szft.tdh/", "SzftWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://200.100.48.28:81/court/service/SzftWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SzftWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://200.100.48.28:81/court/service/SzftWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SzftWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SzftWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SzftWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SzftWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SzftWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SzftWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SzftWebService
     */
    @WebEndpoint(name = "SzftWebServicePort")
    public SzftWebService getSzftWebServicePort() {
        return super.getPort(SzftWebServicePort, SzftWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SzftWebService
     */
    @WebEndpoint(name = "SzftWebServicePort")
    public SzftWebService getSzftWebServicePort(WebServiceFeature... features) {
        return super.getPort(SzftWebServicePort, SzftWebService.class, features);
    }

}
